sjones@acorn:~/acorn-app$ sudo journalctl -u acorn.service -n 200
Mar 28 23:11:43 acorn gunicorn[7974]:     db.create_all()
Mar 28 23:11:43 acorn gunicorn[7974]:   File "/home/sjones/acorn-app/venv/lib/python3.11/site-packages/flask_sqlalchemy/extension.py", li>
Mar 28 23:11:43 acorn gunicorn[7974]:     self._call_for_binds(bind_key, "create_all")
Mar 28 23:11:43 acorn gunicorn[7974]:   File "/home/sjones/acorn-app/venv/lib/python3.11/site-packages/flask_sqlalchemy/extension.py", li>
Mar 28 23:11:43 acorn gunicorn[7974]:     getattr(metadata, op_name)(bind=engine)
Mar 28 23:11:43 acorn gunicorn[7974]:   File "/home/sjones/acorn-app/venv/lib/python3.11/site-packages/sqlalchemy/sql/schema.py", line 59>
Mar 28 23:11:43 acorn gunicorn[7974]:     bind._run_ddl_visitor(
Mar 28 23:11:43 acorn gunicorn[7974]:   File "/home/sjones/acorn-app/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3>
Mar 28 23:11:43 acorn gunicorn[7974]:     conn._run_ddl_visitor(visitorcallable, element, **kwargs)
Mar 28 23:11:43 acorn gunicorn[7974]:   File "/home/sjones/acorn-app/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2>
Mar 28 23:11:43 acorn gunicorn[7974]:     visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
Mar 28 23:11:43 acorn gunicorn[7974]:   File "/home/sjones/acorn-app/venv/lib/python3.11/site-packages/sqlalchemy/sql/visitors.py", line >
Mar 28 23:11:43 acorn gunicorn[7974]:     return meth(obj, **kw)
Mar 28 23:11:43 acorn gunicorn[7974]:            ^^^^^^^^^^^^^^^
Mar 28 23:11:43 acorn gunicorn[7974]:   File "/home/sjones/acorn-app/venv/lib/python3.11/site-packages/sqlalchemy/sql/ddl.py", line 981, >
Mar 28 23:11:43 acorn gunicorn[7974]:     self.traverse_single(
Mar 28 23:11:43 acorn gunicorn[7974]:   File "/home/sjones/acorn-app/venv/lib/python3.11/site-packages/sqlalchemy/sql/visitors.py", line >
Mar 28 23:11:43 acorn gunicorn[7974]:     return meth(obj, **kw)
Mar 28 23:11:43 acorn gunicorn[7974]:            ^^^^^^^^^^^^^^^
Mar 28 23:11:43 acorn gunicorn[7974]:   File "/home/sjones/acorn-app/venv/lib/python3.11/site-packages/sqlalchemy/sql/ddl.py", line 1019,>
Mar 28 23:11:43 acorn gunicorn[7974]:     )._invoke_with(self.connection)
Mar 28 23:11:43 acorn gunicorn[7974]:       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 28 23:11:43 acorn gunicorn[7974]:   File "/home/sjones/acorn-app/venv/lib/python3.11/site-packages/sqlalchemy/sql/ddl.py", line 321, >
Mar 28 23:11:43 acorn gunicorn[7974]:     return bind.execute(self)
Mar 28 23:11:43 acorn gunicorn[7974]:            ^^^^^^^^^^^^^^^^^^
Mar 28 23:11:43 acorn gunicorn[7974]:   File "/home/sjones/acorn-app/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1>
Mar 28 23:11:43 acorn gunicorn[7974]:     return meth(
Mar 28 23:11:43 acorn gunicorn[7974]:            ^^^^^
Mar 28 23:11:43 acorn gunicorn[7974]:   File "/home/sjones/acorn-app/venv/lib/python3.11/site-packages/sqlalchemy/sql/ddl.py", line 187, >
Mar 28 23:11:43 acorn gunicorn[7974]:     return connection._execute_ddl(
Mar 28 23:11:43 acorn gunicorn[7974]:            ^^^^^^^^^^^^^^^^^^^^^^^^
Mar 28 23:11:43 acorn gunicorn[7974]:   File "/home/sjones/acorn-app/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1>
Mar 28 23:11:43 acorn gunicorn[7974]:     ret = self._execute_context(
Mar 28 23:11:43 acorn gunicorn[7974]:           ^^^^^^^^^^^^^^^^^^^^^^
Mar 28 23:11:43 acorn gunicorn[7974]:   File "/home/sjones/acorn-app/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1>
Mar 28 23:11:43 acorn gunicorn[7974]:     return self._exec_single_context(
Mar 28 23:11:43 acorn gunicorn[7974]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 28 23:11:43 acorn gunicorn[7974]:   File "/home/sjones/acorn-app/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1>
Mar 28 23:11:43 acorn gunicorn[7974]:     self._handle_dbapi_exception(
Mar 28 23:11:43 acorn gunicorn[7974]:   File "/home/sjones/acorn-app/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2>
Mar 28 23:11:43 acorn gunicorn[7974]:     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
Mar 28 23:11:43 acorn gunicorn[7974]:   File "/home/sjones/acorn-app/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1>
Mar 28 23:11:43 acorn gunicorn[7974]:     self.dialect.do_execute(
Mar 28 23:11:43 acorn gunicorn[7974]:   File "/home/sjones/acorn-app/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", lin>
Mar 28 23:11:43 acorn gunicorn[7974]:     cursor.execute(statement, parameters)
Mar 28 23:11:43 acorn gunicorn[7974]: sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InsufficientPrivilege) permission denied for sche>
Mar 28 23:11:43 acorn gunicorn[7974]: LINE 2: CREATE TABLE "user" (
Mar 28 23:11:43 acorn gunicorn[7974]:                      ^
Mar 28 23:11:43 acorn gunicorn[7974]: [SQL:
Mar 28 23:11:43 acorn gunicorn[7974]: CREATE TABLE "user" (
Mar 28 23:11:43 acorn gunicorn[7974]:         id SERIAL NOT NULL,
Mar 28 23:11:43 acorn gunicorn[7974]:         username VARCHAR(64) NOT NULL,
Mar 28 23:11:43 acorn gunicorn[7974]:         email VARCHAR(120) NOT NULL,
Mar 28 23:11:43 acorn gunicorn[7974]:         password_hash VARCHAR(256) NOT NULL,
Mar 28 23:11:43 acorn gunicorn[7974]:         is_admin BOOLEAN,
Mar 28 23:11:43 acorn gunicorn[7974]:         first_name VARCHAR(50),
lines 1-56